// Code generated by protoc-gen-go. DO NOT EDIT.
// source: katib.proto

/*
Package api_v1_alpha3 is a generated protocol buffer package.

It is generated from these files:
	katib.proto

It has these top-level messages:
	GetKatibSuggestionsRequest
	GetKatibSuggestionsReply
*/
package api_v1_alpha3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetKatibSuggestionsRequest struct {
}

func (m *GetKatibSuggestionsRequest) Reset()                    { *m = GetKatibSuggestionsRequest{} }
func (m *GetKatibSuggestionsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetKatibSuggestionsRequest) ProtoMessage()               {}
func (*GetKatibSuggestionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetKatibSuggestionsReply struct {
}

func (m *GetKatibSuggestionsReply) Reset()                    { *m = GetKatibSuggestionsReply{} }
func (m *GetKatibSuggestionsReply) String() string            { return proto.CompactTextString(m) }
func (*GetKatibSuggestionsReply) ProtoMessage()               {}
func (*GetKatibSuggestionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*GetKatibSuggestionsRequest)(nil), "api.v1.alpha3.GetKatibSuggestionsRequest")
	proto.RegisterType((*GetKatibSuggestionsReply)(nil), "api.v1.alpha3.GetKatibSuggestionsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KatibSuggestion service

type KatibSuggestionClient interface {
	GetSuggestions(ctx context.Context, in *GetKatibSuggestionsRequest, opts ...grpc.CallOption) (*GetKatibSuggestionsReply, error)
}

type katibSuggestionClient struct {
	cc *grpc.ClientConn
}

func NewKatibSuggestionClient(cc *grpc.ClientConn) KatibSuggestionClient {
	return &katibSuggestionClient{cc}
}

func (c *katibSuggestionClient) GetSuggestions(ctx context.Context, in *GetKatibSuggestionsRequest, opts ...grpc.CallOption) (*GetKatibSuggestionsReply, error) {
	out := new(GetKatibSuggestionsReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha3.KatibSuggestion/GetSuggestions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KatibSuggestion service

type KatibSuggestionServer interface {
	GetSuggestions(context.Context, *GetKatibSuggestionsRequest) (*GetKatibSuggestionsReply, error)
}

func RegisterKatibSuggestionServer(s *grpc.Server, srv KatibSuggestionServer) {
	s.RegisterService(&_KatibSuggestion_serviceDesc, srv)
}

func _KatibSuggestion_GetSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKatibSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KatibSuggestionServer).GetSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha3.KatibSuggestion/GetSuggestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KatibSuggestionServer).GetSuggestions(ctx, req.(*GetKatibSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KatibSuggestion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.alpha3.KatibSuggestion",
	HandlerType: (*KatibSuggestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuggestions",
			Handler:    _KatibSuggestion_GetSuggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "katib.proto",
}

func init() { proto.RegisterFile("katib.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x4e, 0x2c, 0xc9,
	0x4c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4d, 0x2c, 0xc8, 0xd4, 0x2b, 0x33, 0xd4,
	0x4b, 0xcc, 0x29, 0xc8, 0x48, 0x34, 0x96, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f,
	0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28,
	0x56, 0x92, 0xe1, 0x92, 0x72, 0x4f, 0x2d, 0xf1, 0x06, 0x69, 0x0f, 0x2e, 0x4d, 0x4f, 0x4f, 0x2d,
	0x06, 0x4b, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x49, 0x71, 0x49, 0x60, 0x95, 0x2d,
	0xc8, 0xa9, 0x34, 0x2a, 0xe7, 0xe2, 0x47, 0x93, 0x10, 0x4a, 0xe1, 0xe2, 0x73, 0x4f, 0x2d, 0x41,
	0x52, 0x29, 0xa4, 0xa9, 0x87, 0xe2, 0x18, 0x3d, 0xdc, 0x76, 0x49, 0xa9, 0x13, 0xa3, 0xb4, 0x20,
	0xa7, 0x32, 0x89, 0x0d, 0xec, 0x72, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0x12, 0xd6,
	0x96, 0xf5, 0x00, 0x00, 0x00,
}
