# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import advisor_pb2 as advisor__pb2


class AdvisorSuggestionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSuggestions = channel.unary_unary(
        '/api.v1.alpha3.AdvisorSuggestion/GetSuggestions',
        request_serializer=advisor__pb2.GetAdvisorSuggestionsRequest.SerializeToString,
        response_deserializer=advisor__pb2.GetAdvisorSuggestionsReply.FromString,
        )


class AdvisorSuggestionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSuggestions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdvisorSuggestionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSuggestions': grpc.unary_unary_rpc_method_handler(
          servicer.GetSuggestions,
          request_deserializer=advisor__pb2.GetAdvisorSuggestionsRequest.FromString,
          response_serializer=advisor__pb2.GetAdvisorSuggestionsReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.v1.alpha3.AdvisorSuggestion', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
