# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import katib_pb2 as katib__pb2


class KatibSuggestionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSuggestions = channel.unary_unary(
        '/api.v1.alpha3.KatibSuggestion/GetSuggestions',
        request_serializer=katib__pb2.GetKatibSuggestionsRequest.SerializeToString,
        response_deserializer=katib__pb2.GetKatibSuggestionsReply.FromString,
        )


class KatibSuggestionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSuggestions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KatibSuggestionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSuggestions': grpc.unary_unary_rpc_method_handler(
          servicer.GetSuggestions,
          request_deserializer=katib__pb2.GetKatibSuggestionsRequest.FromString,
          response_serializer=katib__pb2.GetKatibSuggestionsReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.v1.alpha3.KatibSuggestion', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
